### ISSUE TITLE
Possible test failure: ReferenceError: resolvedArgv is not defined

### ISSUE THREAD

**Issue by santanubasu** [bahmutov/really-need#17]
I was noticing an error in my own project, so I cloned really-need and ran the tests, but am seeing errors such as this:

ReferenceError: resolvedArgv is not defined
    at Module.eval (eval at <anonymous> (/home/sbasu/workspace-idea/really-need/index.js:115:45), <anonymous>:68:10)
    at Module._compile (/home/sbasu/workspace-idea/really-need/index.js:127:31)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at Module.reallyNeedRequire [as require] (/home/sbasu/workspace-idea/really-need/index.js:94:25)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/sbasu/workspace-idea/really-need/test/simple.js:8:11)
    at Module._compile (module.js:456:26)

Essentially the eval'ed version of Module's _compile is failing due to the resolvedArg being undefined.  As far as I can tell, the original _compile knows about this var because it's declared in the scope that _compile is.  But when _compile is replaced, this isn't the case anymore looks like.

This is using Node 0.10.33, and the error above is if I just run the simple.js test.

**Comment by bahmutov** [comment]
ok, will need to install node 0.10 and try it, weird that Travis runs on 0.10 but does not fail

**Comment by santanubasu** [comment]
BTW, if I simply add 

var resolvedArgv;

to index.js, things work for me.  At least, works for the use of really-need from within my own projects, and also the simple.js test passes.

Not sure if that is really a fix, just something I tried out

**Comment by santanubasu** [comment]
Found one more clue for you.  This happens only when running the code in a debugger (Intellij in my case).  That triggers the following code path inside the compile function:

  if (global.v8debug) {
    if (!resolvedArgv) {
      // we enter the repl if we're not given a filename argument.
      if (process.argv[1]) {
        resolvedArgv = Module._resolveFilename(process.argv[1], null);
      } else {
        resolvedArgv = 'repl';
      }
    }

    // Set breakpoint on module start
    if (filename === resolvedArgv) {
      global.v8debug.Debug.setBreakPoint(compiledWrapper, 0, 0);
    }
  }

All references to resolvedArgv are inside that block.  This probably explains why tests are passing on travis.  So this may not be an issue on a production system, but it might still be worth looking into a fix for people wishing to debug a system using really-need.

**Comment by bahmutov** [comment]
cool, thank you very much for finding the debugger condition. Maybe it
makes sense for you to try writing a PR with a fix that solves the debugger
and the general case? Gleb

**Comment by santanubasu** [comment]
I'm using your code as a basis for a more customized but related utility I'm writing.  In that I'm going to test out some changes like the one I described.  If it looks like they form a PR that will work in the general case, I'll submit that here.  So far it seems like simply defining that var solves it, but need to step through the code a bit more thoroughly to convince myself.
