### ISSUE TITLE
Question: really-need vs proxyquire

### ISSUE THREAD

**Issue by mateatslc** [bahmutov/really-need#28]
How `really-need` differs from [`proxyquire`](https://www.npmjs.com/package/proxyquire)?
They seem to be really similar in features. Any pros/cons using `really-need` over `proxyquire`?

**Comment by bahmutov** [comment]
I am personal ;) I really (pun!) like the simplicity of really-need API 
plus once someone replaces the require with really-need it becomes available everywhere. I should probably make a feature comparison table ...

**Comment by mateatslc** [comment]
Thanks, that makes sense. I'll stick with `really-need` as I don't really need (wooh!) `proxyquire` ;)

**Comment by bahmutov** [comment]
hahaha
