### ISSUE TITLE
Asynchronous pre hook

### ISSUE THREAD

**Issue by m-a-r-c-e-l-i-n-o** [bahmutov/really-need#34]
Hello, awesome module!

I have a requirement and wanted to check in with you before making a pr. Would you be willing to have the pre function below also accept a promise as its return value? 

```
pre: function (source, filename) {
    // transform the source before compiling it
    return source;
},
```

**Comment by bahmutov** [comment]
that's a good idea, BUT the `require` call HAS to return synchronously in Node. That is - you cannot wait for a promise, you have to return a value to the caller

``` js
var m = require('module');
// NOT
require('module').then((m) => ...)
```

**Comment by m-a-r-c-e-l-i-n-o** [comment]
Yeah, you are totally right. Sorry about that.

**Comment by bahmutov** [comment]
no worries, this is why we discuss things!
